### ISSUE TITLE
`lowdb` errors if the directory for db file does not exist

### ISSUE THREAD

**Issue by sarpik** [sarpik/turbo-schedule#21]
It'd be simple to ensure it, using, for example,

```ts
import fs from "fs-extra";
import path from "path";

const dbFilePath = "path/to/database/file";
const dbDirPath  = path.parse(dbFilePath).dir;

fs.ensureDirSync(dbDirPath);
```

but somehow `lowdb` manages to error even before this can complete - does it automatically try to do some operation like reading/writing once it's `import`ed, even before other code can execute?
This would require patching. Oh well, not the first time, I guess..

Example error:

```sh
yarn test
```

```console
yarn run v1.19.1
warning package.json: License should be a valid SPDX license expression
$ yarn test:api --forceExit
warning package.json: License should be a valid SPDX license expression
$ cross-env NODE_ENV=test PORT=5069  jest --config ./test/jest.config.js --forceExit
Error: ENOENT: no such file or directory, open '/home/kipras/projects/turbo-schedule/database/data.test/latest.json'
    at Object.openSync (fs.js:457:3)
    at writeFileSync (fs.js:1298:35)
    at FileSync.read (/home/kipras/projects/turbo-schedule/node_modules/lowdb/adapters/FileSync.js:46:9)
    at LodashWrapper.db.read (/home/kipras/projects/turbo-schedule/node_modules/lowdb/lib/main.js:32:21)
    at module.exports (/home/kipras/projects/turbo-schedule/node_modules/lowdb/lib/main.js:51:13)
    at Object.module.exports [as router] (/home/kipras/projects/turbo-schedule/node_modules/json-server/lib/server/router/index.js:36:10)
    at Object.<anonymous> (/home/kipras/projects/turbo-schedule/server/src/server.ts:50:48)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Module._compile (/home/kipras/projects/turbo-schedule/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Current work-around: Create the folder before doing stuff, lol

```sh
rm -rf   database/data.test/
mkdir -p database/data.test/
yarn test
```

**Comment by sarpik** [comment]
Patched this by just `mkdir -p` before calling the script. Will close for now & will re-open later.
